name: Deploy Flutter Web

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href "/fin_assist/"
      
      - name: Debug build output
        run: ls -la build/web
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
          force_orphan: true
      - name: Debug build output
        run: |
              ls -la build/web
      